import type { ModuleDefinition } from '@/types/numerical.types'

export const MODULE_DEFINITIONS: ModuleDefinition[] = [
  {
    id: 'floating-point',
    title: 'Floating Point',
    subtitle: 'Error Analysis',
    description: 'Understand how computers represent real numbers and why floating-point arithmetic introduces errors.',
    icon: '0.1',
    color: '#f59e0b',
    path: '/floating-point',
    prerequisites: [],
    methods: [],
  },
  {
    id: 'root-finding',
    title: 'Root Finding',
    subtitle: 'f(x) = 0',
    description: 'Locate roots of nonlinear equations using iterative numerical methods.',
    icon: '√',
    color: '#10b981',
    path: '/root-finding',
    prerequisites: [],
    methods: [
      { id: 'bisection',       name: 'Bisection',         path: '/root-finding/bisection',       description: 'Bracket and halve the interval containing the root.',       complexity: 'introductory', tags: ['bracket','guaranteed'] },
      { id: 'newton-raphson',  name: 'Newton–Raphson',    path: '/root-finding/newton-raphson',   description: 'Quadratic convergence using the derivative.',                complexity: 'intermediate', tags: ['open','fast','derivative'] },
      { id: 'secant',          name: 'Secant Method',     path: '/root-finding/secant',           description: 'Newton without explicit derivative — uses finite differences.', complexity: 'intermediate', tags: ['open','no-derivative'] },
      { id: 'fixed-point',     name: 'Fixed-Point',       path: '/root-finding/fixed-point',      description: 'Iterates g(x) = x until convergence.',                      complexity: 'introductory', tags: ['open','simple'] },
      { id: 'comparison',      name: 'Method Comparison', path: '/root-finding/comparison',       description: 'Compare all root-finding methods side by side.',             complexity: 'intermediate', tags: ['comparison'] },
    ],
  },
  {
    id: 'interpolation',
    title: 'Interpolation',
    subtitle: 'Curve Fitting',
    description: 'Construct smooth curves passing through given data points.',
    icon: '~',
    color: '#3b82f6',
    path: '/interpolation',
    prerequisites: [],
    methods: [
      { id: 'lagrange',            name: 'Lagrange',              path: '/interpolation/lagrange',             description: 'Polynomial through n+1 points using Lagrange basis polynomials.', complexity: 'intermediate', tags: ['polynomial'] },
      { id: 'newton-divided-diff', name: 'Newton Divided Diff.',  path: '/interpolation/newton-divided-diff', description: 'Efficient polynomial interpolation using divided differences.',      complexity: 'intermediate', tags: ['polynomial','efficient'] },
      { id: 'cubic-spline',        name: 'Cubic Spline',          path: '/interpolation/cubic-spline',         description: 'Piecewise cubic polynomials with continuous second derivatives.',  complexity: 'advanced',      tags: ['spline','smooth'] },
      { id: 'comparison',          name: 'Method Comparison',     path: '/interpolation/comparison',           description: 'Compare interpolation methods on the same dataset.',              complexity: 'intermediate', tags: ['comparison'] },
    ],
  },
  {
    id: 'differentiation',
    title: 'Differentiation',
    subtitle: 'Numerical Derivatives',
    description: 'Approximate derivatives of functions defined by data or formulas.',
    icon: "f'",
    color: '#8b5cf6',
    path: '/differentiation',
    prerequisites: [],
    methods: [
      { id: 'forward',    name: 'Forward Difference',   path: '/differentiation/forward',    description: 'First-order forward finite difference approximation.',       complexity: 'introductory', tags: ['O(h)'] },
      { id: 'backward',   name: 'Backward Difference',  path: '/differentiation/backward',   description: 'First-order backward finite difference approximation.',      complexity: 'introductory', tags: ['O(h)'] },
      { id: 'central',    name: 'Central Difference',   path: '/differentiation/central',    description: 'Second-order central finite difference approximation.',      complexity: 'introductory', tags: ['O(h²)','accurate'] },
      { id: 'richardson', name: 'Richardson Extrapolation', path: '/differentiation/richardson', description: 'Combine steps to cancel leading error terms.',         complexity: 'advanced',     tags: ['O(h⁴)','high-order'] },
    ],
  },
  {
    id: 'integration',
    title: 'Integration',
    subtitle: 'Numerical Quadrature',
    description: 'Compute definite integrals numerically when analytical solutions are difficult.',
    icon: '∫',
    color: '#ec4899',
    path: '/integration',
    prerequisites: [],
    methods: [
      { id: 'trapezoidal',        name: 'Trapezoidal Rule',      path: '/integration/trapezoidal',        description: 'Approximate area using trapezoids.',                      complexity: 'introductory', tags: ['O(h²)'] },
      { id: 'simpsons',           name: "Simpson's Rule",         path: '/integration/simpsons',           description: 'Parabolic fit over sub-intervals.',                       complexity: 'intermediate', tags: ['O(h⁴)'] },
      { id: 'gaussian-quadrature',name: 'Gaussian Quadrature',   path: '/integration/gaussian-quadrature', description: 'Optimal nodes and weights for polynomial-exact integration.', complexity: 'advanced', tags: ['optimal','exact'] },
      { id: 'comparison',         name: 'Method Comparison',     path: '/integration/comparison',         description: 'Compare integration methods on the same function.',        complexity: 'intermediate', tags: ['comparison'] },
    ],
  },
  {
    id: 'linear-systems',
    title: 'Linear Systems',
    subtitle: 'Ax = b',
    description: 'Solve systems of linear equations using direct and iterative methods.',
    icon: '[A]',
    color: '#14b8a6',
    path: '/linear-systems',
    prerequisites: [],
    methods: [
      { id: 'gaussian-elimination', name: 'Gaussian Elimination',  path: '/linear-systems/gaussian-elimination', description: 'Row reduce the augmented matrix to upper triangular form.',       complexity: 'intermediate', tags: ['direct','exact'] },
      { id: 'gauss-seidel',         name: 'Gauss–Seidel',         path: '/linear-systems/gauss-seidel',         description: 'Iterative method using most-recent values immediately.',          complexity: 'intermediate', tags: ['iterative','large-systems'] },
      { id: 'jacobi',               name: 'Jacobi Method',         path: '/linear-systems/jacobi',               description: 'Classic simultaneous iterative relaxation method.',               complexity: 'introductory', tags: ['iterative','parallel'] },
      { id: 'comparison',           name: 'Method Comparison',     path: '/linear-systems/comparison',           description: 'Compare direct vs iterative solvers.',                          complexity: 'intermediate', tags: ['comparison'] },
    ],
  },
  {
    id: 'lu-decomposition',
    title: 'LU Decomposition',
    subtitle: 'A = LU',
    description: 'Factor a matrix into lower and upper triangular factors for efficient solving.',
    icon: 'LU',
    color: '#f97316',
    path: '/lu-decomposition',
    prerequisites: ['linear-systems'],
    methods: [
      { id: 'lu',       name: 'LU (Doolittle)',    path: '/lu-decomposition',          description: 'Standard LU factorization with partial pivoting.', complexity: 'intermediate', tags: ['direct','factorization'] },
      { id: 'cholesky', name: 'Cholesky',           path: '/lu-decomposition/cholesky', description: 'Efficient LU for symmetric positive-definite matrices.', complexity: 'advanced', tags: ['symmetric','efficient'] },
    ],
  },
  {
    id: 'optimization',
    title: 'Optimization',
    subtitle: 'min f(x)',
    description: 'Find minima and maxima of functions using numerical search strategies.',
    icon: '↓',
    color: '#06b6d4',
    path: '/optimization',
    prerequisites: ['differentiation'],
    methods: [
      { id: 'golden-section',    name: 'Golden Section Search', path: '/optimization/golden-section',    description: 'Bracket minimum without requiring derivatives.',     complexity: 'introductory', tags: ['bracket','derivative-free'] },
      { id: 'gradient-descent',  name: 'Gradient Descent',      path: '/optimization/gradient-descent',  description: 'Follow the negative gradient to find the minimum.',  complexity: 'intermediate', tags: ['gradient','ML-relevant'] },
      { id: 'comparison',        name: 'Method Comparison',     path: '/optimization/comparison',        description: 'Compare optimization methods on the same objective.', complexity: 'intermediate', tags: ['comparison'] },
    ],
  },
  {
    id: 'ode',
    title: 'ODE Solvers',
    subtitle: "y' = f(x,y)",
    description: 'Numerically integrate ordinary differential equations step by step.',
    icon: 'dy/dx',
    color: '#84cc16',
    path: '/ode',
    prerequisites: ['integration'],
    methods: [
      { id: 'euler',       name: "Euler's Method",    path: '/ode/euler',       description: 'Simplest explicit ODE solver — first-order, fixed step.',            complexity: 'introductory', tags: ['explicit','O(h)'] },
      { id: 'runge-kutta', name: 'Runge–Kutta 4',    path: '/ode/runge-kutta', description: 'Classic fourth-order method with excellent accuracy.',               complexity: 'intermediate', tags: ['explicit','O(h⁴)','standard'] },
      { id: 'comparison',  name: 'Method Comparison', path: '/ode/comparison',  description: 'Compare ODE solvers on accuracy, step size, and phase portrait.', complexity: 'advanced',     tags: ['comparison'] },
    ],
  },
  {
    id: 'performance',
    title: 'Performance Analysis',
    subtitle: 'Benchmarks & Complexity',
    description: 'Compare algorithms on speed, accuracy, convergence rate, and computational cost.',
    icon: '⚡',
    color: '#e11d48',
    path: '/performance',
    prerequisites: [],
    methods: [],
  },
]
